# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run CucumberJava Tests
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: ' env we wanted to run '
        type: choice
        options:
           - main
           - dev
           - stag
           - qa
           - prod
      script_name:
        description: ' test script wanted to execute '
        required: true
        type: choice
        default: 'loginPage'
        options:
           - login
           - GoogleSearch
           - resultsPage
           - addCart
      
jobs:
  build:
    runs-on: ubuntu-latest
       
    env: 
        USERNAME : ${{ secrets.USERNAME }}
        PASSWORD : ${{ secrets.PASSWORD }}   
          

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11' 

      - name: Add execution permission to Chromedriver
        run: chmod +x /home/runner/work/CucumberJava/CucumberJava/src/test/resources/drivers/chromedriver

      - name: Build with Maven
        run: mvn clean install
    
      - name: Run Cucumber Tests
        run: mvn test






    
