name: CucumberJava Tests on windows
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: ' env we wanted to run '
        type: choice
        options:
           - main
           - dev
           - stag
           - qa
           - prod
      script_name:
        description: ' test script wanted to execute '
        required: true
        type: choice
        default: 'InstGoogle'
        options:
           - login
           - InstGoogle
           - resultsPage
           - addCart
      
jobs:
  build:
    runs-on: windows-latest
       
    env: 
        USERNAME : ${{ secrets.USERNAME }}
        PASSWORD : ${{ secrets.PASSWORD }}   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11' 

      - name: Run Cucumber Tests
        run: mvn test