name: CucumberJava Tests on windows
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        description: ' env we wanted to run '
        type: choice
        options:
           - main
           - dev
           - stag
           - qa
           - prod
      script_name:
        description: ' test script wanted to execute '
        required: true
        type: choice
        default: 'InstGoogle'
        options:
           - login
           - InstGoogle
           - resultsPage
           - addCart
      
jobs:
  build:
    runs-on: windows-latest
       
    env: 
        USERNAME : ${{ secrets.USERNAME }}
        PASSWORD : ${{ secrets.PASSWORD }}   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 8u222
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8.0.222'

      - name: Set up ChromeDriver v78.0
        run: |
          Invoke-WebRequest -Uri 'https://chromedriver.storage.googleapis.com/78.0.3904.97/chromedriver_win32.zip' -OutFile 'chromedriver_win32.zip'
          Expand-Archive -Path 'chromedriver_win32.zip' -DestinationPath 'C:\tools'
          [System.Environment]::SetEnvironmentVariable('PATH', "$env:PATH;C:\tools", [System.EnvironmentVariableTarget]::Machine)
          $env:webdriver.chrome.driver = 'C:\tools\chromedriver.exe'

      - name: Set up Chrome
        uses: sarvesh-only/actions/setup-chrome@v2

      - name: Run Cucumber Tests
        run: mvn test